sudo: required
dist: xenial
language: minimal

services:
  - docker

before_script:
  - docker-compose up --build -d

script:
  - ./run_docker_tests.sh

after_script:
  - docker-compose down

notifications:
  email:
    recipients:
      - engineering@flickswitch.co.za
    on_success: change
    on_failure: change
